version: '3'

services:
  api:
    build: ./backend
    container_name: fast_api
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  front:
    build: ./frontend
    container_name: fast_front
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
      - /app/build
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    depends_on:
      - api

  db:
    image: mongo
    container_name: fast_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./docker/mongo:/data/db

  redis:
    image: redis:6.2.6
    container_name: fast_redis
    command: redis-server
    ports: 
      - "6379:6379"
